# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
#  Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  labels:
    app: postgres-db
    tier: db
spec:
  selector:
    matchLabels:
      app: postgres-db
      tier: db
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-db
        tier: db
    spec:
      containers:
        - name: postgres-db
          image: postgres
          imagePullPolicy: Always
          ports:
            - name: 5432tcp
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: postgres-db-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
      volumes:
        - name: postgres-db-data
          persistentVolumeClaim:
            claimName: postgres-db-pvc




