
# Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
    app: postgres-db
    tier: db
spec:
  ports:
    - name: 5432tcp
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-db
    tier: db
  type: ClusterIP